[project]
name = "scripts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "arq>=0.26.3",
]
[project.scripts]
ingest_logs = "ingest_logs:main"
dummy_server = "dummy_server:run_server"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
include = ["ingest_logs.py", "dummy_server.py"]
